# Generated by Django 4.0.4 on 2022-07-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0007_producto_imagen_useritem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreP',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
    ]
