# Generated by Django 4.0.4 on 2022-07-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0008_rename_idproducto_producto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidadInventario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
